model_params:
  mistral: # https://huggingface.co/mistralai/Mistral-Small-3.2-24B-Instruct-2506/blob/main/generation_config.json
    path: "/path/to/Mistral-Small-3.2-24B-Instruct-2506-IQ4_NL.gguf"
    temperature: 0.15
    top_p: 0.95
    eot_token: "</s>"
  llama: # https://huggingface.co/meta-llama/Llama-4-Scout-17B-16E-Instruct/blob/main/generation_config.json
    path: "/path/to/Llama-4-Scout-17B-16E-Instruct-IQ4_NL-00001-of-00002.gguf"
    temperature: 0.6
    top_p: 0.9
    eot_token: "<|eot_id|>"
  cohere: # https://docs.cohere.com/docs/temperature
    path: "/path/to/CohereForAI_c4ai-command-a-03-2025-IQ4_NL-00001-of-00002.gguf"
    temperature: 0.3
    top_p: 0.95
    eot_token: "<|END_OF_TURN_TOKEN|>"
  openai: # https://github.com/openai/gpt-oss/blob/main/gpt_oss/evals/__main__.py
    path: "/path/to/openai_gpt-oss-120b-IQ4_NL-00001-of-00002.gguf"
    temperature: 1.0
    top_p: 1.0
    eot_token: "<|endoftext|>"
  qwen: # https://huggingface.co/Qwen/Qwen3-Next-80B-A3B-Instruct/blob/main/generation_config.json
    path: "/path/to/Qwen3-30B-A3B-Instruct-2507-IQ4_NL.gguf"
    temperature: 0.7
    top_p: 0.8
    eot_token: "<|im_end|>"
generation_params:
  n_probs: 10
  n_predict: 2048
  seed: 42
  batch_size: 10